version: '3.8'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=myuser
      - DOCKER_INFLUXDB_INIT_PASSWORD=mypassword
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=myadmintoken
    volumes:
      - influxdb-data:/var/lib/influxdb

  mock-server:
    build:
      context: ./mock_server
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    command: "uvicorn main:app --host 0.0.0.0 --reload"
    volumes:
      - ./mock_server:/app

#  test-env:
#    build:
#      context: ./tests
#      dockerfile: Dockerfile
#    container_name: test-env
#    volumes:
#      - ./tests:/app


volumes:
  influxdb-data: